### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by ThomasThelen** [HungryHippos-CS4700/KoalasInGuatemala#1]
I'd like to control a gun wielding Koala and defend the Tree of Life. How can I play?

**Comment by matthewkhle** [comment]
# Koalas In Guatemala
Koalas in Guatemala is a fast-paced 2D action arcade game where the player controls a gun wielding koala while defending its home, the tree of life.

## PC/Mac Build (recommended for the best experience)
https://drive.google.com/drive/folders/11dxvx0f7Cjb3hPsNDDP239WBJctblJ_b?usp=sharing
1. right click folder -> download
2. extract files, run Koalas in Guatemala.exe


## WebGL Build
https://hungryhippos-cs4700.github.io/KoalasInGuatemala/

**Comment by Daarrik** [comment]
Thanks for taking interest in our small college game dev project lol
You can find the PC build [here](https://drive.google.com/drive/folders/11dxvx0f7Cjb3hPsNDDP239WBJctblJ_b).
Hope you find what little game it is fun!
